### ISSUE TITLE
Enhance DB schema to include one time tokens

### ISSUE THREAD

**Issue by jslopezgithub** [jslopezgithub/cnca#25]
The tokens used for forgot password should be stored in the database to avoid problems when using multiple servers or issues across reboots of the server.

**Comment by aliskhanoff** [comment]
@jslopezgithub Is not clear. Please explain what is meaning?

**Comment by jslopezgithub** [comment]
When you send a link for a password reset, the link should work only once. Typically you send the link with another parameter with a random value. (One time token). This token value is associated with the information required to reset the password or to verify the user owns the email.
