### ISSUE TITLE
Implement a generic db insert function

### ISSUE THREAD

**Issue by xmichele** [jslopezgithub/cnca#8]
In example a function boolean insert(table name, key, valuesList). So that once we define our tables we can reuse it to insert db rows among the tables we'll define.
In example for the table name "Users"

myCodiceFiscale is the key and the values are name1, surname1, birthPlace1, birthDate1, activityCategory1,  etc ..

Returns true if correctly inserted , otherwise false or exception.
Nice to have: validation about values types and/or ranges (i.e. date-based , length-based )

**Comment by jslopezgithub** [comment]
Guys, once you have something you can store it in GitHub so that we can
review and give you some feedback. Maybe inside a docs folders.

**Comment by aliskhanoff** [comment]
@xmichele I using now ORM (object relation mapper) which can do all the things. [(sequelize)](https://sequelize.readthedocs.io/en/v3/) Is doing everything what we need in this project
